### ISSUE TITLE
Why the static resource not found ?

### ISSUE THREAD

**Issue by shenbinglife** [bootique-examples/bootique-mvc-demo#2]
In this demo , the static resource "http://localhost:9999/styles.css" is not found.
it returns 404.

I do not change any files before run.

**Comment by const1993** [comment]
Hello, thanks for your report. 
The problem is already solved. 
Now you can reach styles.css with url: http://localhost:9999/css/styles.css

**Comment by aqiu202** [comment]
In my demo , it doesn't work too ,Why?

**Comment by const1993** [comment]
Hi, sorry for that. Fix now merged into master. Please pull last changes and try again.
